2023-10-12 18:26:26.493 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 18:26:26.534 [info] [Error - 18:26:26] Server initialization failed.
2023-10-12 18:26:26.534 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:26:26.534 [info] [Info  - 18:26:26] Connection to server got closed. Server will restart.
2023-10-12 18:26:26.534 [info] true
2023-10-12 18:26:26.534 [info] [Error - 18:26:26] Python Jedi client: couldn't create connection to server.
2023-10-12 18:26:26.534 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:26:26.570 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-12 18:26:26.570 [info]     from jedi_language_server.cli import cli

2023-10-12 18:26:26.571 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 18:26:26.573 [info] [Error - 18:26:26] Server initialization failed.
2023-10-12 18:26:26.573 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:26:26.574 [info] [Info  - 18:26:26] Connection to server got closed. Server will restart.
2023-10-12 18:26:26.574 [info] true
2023-10-12 18:26:26.574 [info] [Error - 18:26:26] Python Jedi client: couldn't create connection to server.
2023-10-12 18:26:26.574 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:26:26.592 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-12 18:26:26.592 [info]     from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 18:26:26.594 [info] [Error - 18:26:26] Server initialization failed.
2023-10-12 18:26:26.594 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:26:26.594 [info] [Info  - 18:26:26] Connection to server got closed. Server will restart.
2023-10-12 18:26:26.595 [info] true
2023-10-12 18:26:26.595 [info] [Error - 18:26:26] Python Jedi client: couldn't create connection to server.
2023-10-12 18:26:26.595 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:26:26.595 [info] [Error - 18:26:26] Restarting server failed
2023-10-12 18:26:26.595 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:26:26.618 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-12 18:26:26.618 [info]     from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 18:26:26.620 [info] [Error - 18:26:26] Server initialization failed.
2023-10-12 18:26:26.620 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:26:26.620 [info] [Info  - 18:26:26] Connection to server got closed. Server will restart.
2023-10-12 18:26:26.620 [info] true
2023-10-12 18:26:26.621 [info] [Error - 18:26:26] Python Jedi client: couldn't create connection to server.
2023-10-12 18:26:26.621 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:26:26.621 [info] [Error - 18:26:26] Restarting server failed
2023-10-12 18:26:26.621 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:26:26.638 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 18:26:26.640 [info] [Error - 18:26:26] Server initialization failed.
2023-10-12 18:26:26.640 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:26:26.640 [info] [Error - 18:26:26] The Python Jedi server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-10-12 18:26:26.640 [info] [Error - 18:26:26] Python Jedi client: couldn't create connection to server.
2023-10-12 18:26:26.640 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:26:26.640 [info] [Error - 18:26:26] Restarting server failed
2023-10-12 18:26:26.640 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
