2023-10-12 20:16:29.844 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-12 20:16:29.860 [info]     from jedi_language_server.cli import cli

2023-10-12 20:16:29.865 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 20:16:29.901 [info] [Error - 20:16:29] Server initialization failed.
2023-10-12 20:16:29.901 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 20:16:29.901 [info] [Info  - 20:16:29] Connection to server got closed. Server will restart.
2023-10-12 20:16:29.901 [info] true
2023-10-12 20:16:29.902 [info] [Error - 20:16:29] Python Jedi client: couldn't create connection to server.
2023-10-12 20:16:29.902 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 20:16:29.932 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 20:16:29.934 [info] [Error - 20:16:29] Server initialization failed.
2023-10-12 20:16:29.934 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 20:16:29.934 [info] [Info  - 20:16:29] Connection to server got closed. Server will restart.
2023-10-12 20:16:29.934 [info] true
2023-10-12 20:16:29.935 [info] [Error - 20:16:29] Python Jedi client: couldn't create connection to server.
2023-10-12 20:16:29.935 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 20:16:29.968 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli

2023-10-12 20:16:29.968 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 20:16:29.971 [info] [Error - 20:16:29] Server initialization failed.
2023-10-12 20:16:29.971 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 20:16:29.971 [info] [Info  - 20:16:29] Connection to server got closed. Server will restart.
2023-10-12 20:16:29.971 [info] true
2023-10-12 20:16:29.971 [info] [Error - 20:16:29] Python Jedi client: couldn't create connection to server.
2023-10-12 20:16:29.971 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 20:16:29.971 [info] [Error - 20:16:29] Restarting server failed
2023-10-12 20:16:29.971 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 20:16:29.998 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 20:16:30.000 [info] [Error - 20:16:30] Server initialization failed.
2023-10-12 20:16:30.001 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 20:16:30.001 [info] [Info  - 20:16:30] Connection to server got closed. Server will restart.
2023-10-12 20:16:30.001 [info] true
2023-10-12 20:16:30.001 [info] [Error - 20:16:30] Python Jedi client: couldn't create connection to server.
2023-10-12 20:16:30.001 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 20:16:30.001 [info] [Error - 20:16:30] Restarting server failed
2023-10-12 20:16:30.001 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 20:16:30.025 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-12 20:16:30.026 [info]     from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 20:16:30.029 [info] [Error - 20:16:30] Server initialization failed.
2023-10-12 20:16:30.029 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 20:16:30.029 [info] [Error - 20:16:30] The Python Jedi server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-10-12 20:16:30.029 [info] [Error - 20:16:30] Python Jedi client: couldn't create connection to server.
2023-10-12 20:16:30.029 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 20:16:30.029 [info] [Error - 20:16:30] Restarting server failed
2023-10-12 20:16:30.029 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
