2023-10-12 11:55:25.366 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 11:55:25.380 [info] [Error - 11:55:25] Server initialization failed.
2023-10-12 11:55:25.380 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 11:55:25.380 [info] [Info  - 11:55:25] Connection to server got closed. Server will restart.
2023-10-12 11:55:25.380 [info] true
2023-10-12 11:55:25.381 [info] [Error - 11:55:25] Python Jedi client: couldn't create connection to server.
2023-10-12 11:55:25.381 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 11:55:25.417 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 11:55:25.419 [info] [Error - 11:55:25] Server initialization failed.
2023-10-12 11:55:25.419 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 11:55:25.419 [info] [Info  - 11:55:25] Connection to server got closed. Server will restart.
2023-10-12 11:55:25.419 [info] true
2023-10-12 11:55:25.419 [info] [Error - 11:55:25] Python Jedi client: couldn't create connection to server.
2023-10-12 11:55:25.419 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 11:55:25.468 [info] [Error - 11:55:25] Client Python Jedi: connection to server is erroring. Shutting down server.
2023-10-12 11:55:25.469 [info] [Error - 11:55:25] Stopping server failed
2023-10-12 11:55:25.469 [info] Error: Client is not running and can't be stopped. It's current state is: startFailed
	at E.shutdown (/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/out/client/extension.js:2:2080806)
	at E.stop (/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/out/client/extension.js:2:2080387)
	at E.stop (/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/out/client/extension.js:2:2242667)
	at E.handleConnectionError (/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/out/client/extension.js:2:2086894)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-12 11:55:25.476 [info] [Error - 11:55:25] Server initialization failed.
2023-10-12 11:55:25.476 [info]   Message: write EPIPE
  Code: -32099 
2023-10-12 11:55:25.476 [info] [Error - 11:55:25] Python Jedi client: couldn't create connection to server.
2023-10-12 11:55:25.476 [info]   Message: write EPIPE
  Code: -32099 
2023-10-12 11:55:25.477 [info] [Error - 11:55:25] Restarting server failed
2023-10-12 11:55:25.477 [info]   Message: write EPIPE
  Code: -32099 
2023-10-12 11:55:25.477 [info] [Error - 11:55:25] Restarting server failed
2023-10-12 11:55:25.477 [info]   Message: write EPIPE
  Code: -32099 
2023-10-12 11:55:25.477 [info] [Info  - 11:55:25] Connection to server got closed. Server will restart.
2023-10-12 11:55:25.477 [info] true
2023-10-12 11:55:25.485 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 11:55:25.536 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 11:55:25.539 [info] [Error - 11:55:25] Server initialization failed.
2023-10-12 11:55:25.539 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 11:55:25.539 [info] [Info  - 11:55:25] Connection to server got closed. Server will restart.
2023-10-12 11:55:25.539 [info] true
2023-10-12 11:55:25.539 [info] [Error - 11:55:25] Python Jedi client: couldn't create connection to server.
2023-10-12 11:55:25.539 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 11:55:25.600 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 11:55:25.601 [info] [Error - 11:55:25] Server initialization failed.
2023-10-12 11:55:25.601 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 11:55:25.601 [info] [Error - 11:55:25] The Python Jedi server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-10-12 11:55:25.601 [info] [Error - 11:55:25] Python Jedi client: couldn't create connection to server.
2023-10-12 11:55:25.601 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 11:55:25.602 [info] [Error - 11:55:25] Restarting server failed
2023-10-12 11:55:25.602 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
